language: node_js
cache: npm
notifications:
  email: false
node_js:
  - 10.14
  - 12
install: npm install
branches:
  only: master

jobs:
  include:
    - stage: testing
      if: branch in (master, develop)
      env:
        - TEST=test
      script:
        - npm run validate
      after_success:
        - mv coverage/coverage-final.json coverage/coverage.json
        - codecov

    - stage: release
      if: branch = master AND commit_message =~ /^[0-9]*\.[0-9]*\.[0-9]*$/
      node_js: 12
      before_deploy:
        - npm run build
        - echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        cleanup: true
        tags: true
